<?php
/*
    |--------------------------------------------------------------------------
    | List of countries
    |--------------------------------------------------------------------------
    |
    | This value is the name of your application. This value is used when the
    | framework needs to place the application's name in a notification or
    | any other location as required by the application or its packages.
    |
    */

return [
    "list" => [
        array(
            'name' => 'Afghanistan',
            'code' => 'AF',
            'timezone' => 'Afghanistan Standard Time',
            'utc' => 'UTC+04:30',
            'mobileCode' => '+93',
        ),
        array(
            'name' => 'Åland Islands',
            'code' => 'AX',
            'timezone' => 'FLE Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+358-18',
        ),
        array(
            'name' => 'Albania',
            'code' => 'AL',
            'timezone' => 'Central Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+355',
        ),
        array(
            'name' => 'Algeria',
            'code' => 'DZ',
            'timezone' => 'W. Central Africa Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+213',
        ),
        array(
            'name' => 'American Samoa',
            'code' => 'AS',
            'timezone' => 'UTC-11',
            'utc' => 'UTC-11:00',
            'mobileCode' => '+1-684',
        ),
        array(
            'name' => 'Andorra',
            'code' => 'AD',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+376',
        ),
        array(
            'name' => 'Angola',
            'code' => 'AO',
            'timezone' => 'W. Central Africa Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+244',
        ),
        array(
            'name' => 'Anguilla',
            'code' => 'AI',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+1-264',
        ),
        array(
            'name' => 'Antarctica',
            'code' => 'AQ',
            'timezone' => 'Pacific SA Standard Time',
            'utc' => 'UTC-03:00',
            'mobileCode' => '+',
        ),
        array(
            'name' => 'Antigua and Barbuda',
            'code' => 'AG',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+1-268',
        ),
        array(
            'name' => 'Argentina',
            'code' => 'AR',
            'timezone' => 'Argentina Standard Time',
            'utc' => 'UTC-03:00',
            'mobileCode' => '+54',
        ),
        array(
            'name' => 'Armenia',
            'code' => 'AM',
            'timezone' => 'Caucasus Standard Time',
            'utc' => 'UTC+04:00',
            'mobileCode' => '+374',
        ),
        array(
            'name' => 'Aruba',
            'code' => 'AW',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+297',
        ),
        array(
            'name' => 'Australia',
            'code' => 'AU',
            'timezone' => 'AUS Eastern Standard Time',
            'utc' => 'UTC+10:00',
            'mobileCode' => '+61',
        ),
        array(
            'name' => 'Austria',
            'code' => 'AT',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+43',
        ),
        array(
            'name' => 'Azerbaijan',
            'code' => 'AZ',
            'timezone' => 'Azerbaijan Standard Time',
            'utc' => 'UTC+04:00',
            'mobileCode' => '+994',
        ),
        array(
            'name' => 'Bahamas, The',
            'code' => 'BS',
            'timezone' => 'Eastern Standard Time',
            'utc' => 'UTC-05:00',
            'mobileCode' => '+1-242',
        ),
        array(
            'name' => 'Bahrain',
            'code' => 'BH',
            'timezone' => 'Arab Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+973',
        ),
        array(
            'name' => 'Bangladesh',
            'code' => 'BD',
            'timezone' => 'Bangladesh Standard Time',
            'utc' => 'UTC+06:00',
            'mobileCode' => '+880',
        ),
        array(
            'name' => 'Barbados',
            'code' => 'BB',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+1-246',
        ),
        array(
            'name' => 'Belarus',
            'code' => 'BY',
            'timezone' => 'Belarus Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+375',
        ),
        array(
            'name' => 'Belgium',
            'code' => 'BE',
            'timezone' => 'Romance Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+32',
        ),
        array(
            'name' => 'Belize',
            'code' => 'BZ',
            'timezone' => 'Central America Standard Time',
            'utc' => 'UTC-06:00',
            'mobileCode' => '+501',
        ),
        array(
            'name' => 'Benin',
            'code' => 'BJ',
            'timezone' => 'W. Central Africa Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+229',
        ),
        array(
            'name' => 'Bermuda',
            'code' => 'BM',
            'timezone' => 'Atlantic Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+1-441',
        ),
        array(
            'name' => 'Bhutan',
            'code' => 'BT',
            'timezone' => 'Bangladesh Standard Time',
            'utc' => 'UTC+06:00',
            'mobileCode' => '+975',
        ),
        array(
            'name' => 'Bolivarian Republic of Venezuela',
            'code' => 'VE',
            'timezone' => 'Venezuela Standard Time',
            'utc' => 'UTC-04:30',
            'mobileCode' => '+58',
        ),
        array(
            'name' => 'Bolivia',
            'code' => 'BO',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+591',
        ),
        array(
            'name' => 'Bonaire, Sint Eustatius and Saba',
            'code' => 'BQ',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+599',
        ),
        array(
            'name' => 'Bosnia and Herzegovina',
            'code' => 'BA',
            'timezone' => 'Central European Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+387',
        ),
        array(
            'name' => 'Botswana',
            'code' => 'BW',
            'timezone' => 'South Africa Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+267',
        ),
        array(
            'name' => 'Bouvet Island',
            'code' => 'BV',
            'timezone' => 'UTC',
            'utc' => 'UTC',
            'mobileCode' => '+',
        ),
        array(
            'name' => 'Brazil',
            'code' => 'BR',
            'timezone' => 'E. South America Standard Time',
            'utc' => 'UTC-03:00',
            'mobileCode' => '+55',
        ),
        array(
            'name' => 'British Indian Ocean Territory',
            'code' => 'IO',
            'timezone' => 'Central Asia Standard Time',
            'utc' => 'UTC+06:00',
            'mobileCode' => '+246',
        ),
        array(
            'name' => 'Brunei',
            'code' => 'BN',
            'timezone' => 'Singapore Standard Time',
            'utc' => 'UTC+08:00',
            'mobileCode' => '+673',
        ),
        array(
            'name' => 'Bulgaria',
            'code' => 'BG',
            'timezone' => 'FLE Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+359',
        ),
        array(
            'name' => 'Burkina Faso',
            'code' => 'BF',
            'timezone' => 'Greenwich Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+226',
        ),
        array(
            'name' => 'Burundi',
            'code' => 'BI',
            'timezone' => 'South Africa Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+257',
        ),
        array(
            'name' => 'Cabo Verde',
            'code' => 'CV',
            'timezone' => 'Cape Verde Standard Time',
            'utc' => 'UTC-01:00',
            'mobileCode' => '+238',
        ),
        array(
            'name' => 'Cambodia',
            'code' => 'KH',
            'timezone' => 'SE Asia Standard Time',
            'utc' => 'UTC+07:00',
            'mobileCode' => '+855',
        ),
        array(
            'name' => 'Cameroon',
            'code' => 'CM',
            'timezone' => 'W. Central Africa Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+237',
        ),
        array(
            'name' => 'Canada',
            'code' => 'CA',
            'timezone' => 'Eastern Standard Time',
            'utc' => 'UTC-05:00',
            'mobileCode' => '+1',
        ),
        array(
            'name' => 'Cayman Islands',
            'code' => 'KY',
            'timezone' => 'SA Pacific Standard Time',
            'utc' => 'UTC-05:00',
            'mobileCode' => '+1-345',
        ),
        array(
            'name' => 'Central African Republic',
            'code' => 'CF',
            'timezone' => 'W. Central Africa Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+236',
        ),
        array(
            'name' => 'Chad',
            'code' => 'TD',
            'timezone' => 'W. Central Africa Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+235',
        ),
        array(
            'name' => 'Chile',
            'code' => 'CL',
            'timezone' => 'Pacific SA Standard Time',
            'utc' => 'UTC-03:00',
            'mobileCode' => '+56',
        ),
        array(
            'name' => 'China',
            'code' => 'CN',
            'timezone' => 'China Standard Time',
            'utc' => 'UTC+08:00',
            'mobileCode' => '+86',
        ),
        array(
            'name' => 'Christmas Island',
            'code' => 'CX',
            'timezone' => 'SE Asia Standard Time',
            'utc' => 'UTC+07:00',
            'mobileCode' => '+61',
        ),
        array(
            'name' => 'Cocos (Keeling) Islands',
            'code' => 'CC',
            'timezone' => 'Myanmar Standard Time',
            'utc' => 'UTC+06:30',
            'mobileCode' => '+61',
        ),
        array(
            'name' => 'Colombia',
            'code' => 'CO',
            'timezone' => 'SA Pacific Standard Time',
            'utc' => 'UTC-05:00',
            'mobileCode' => '+57',
        ),
        array(
            'name' => 'Comoros',
            'code' => 'KM',
            'timezone' => 'E. Africa Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+269',
        ),
        array(
            'name' => 'Congo',
            'code' => 'CG',
            'timezone' => 'W. Central Africa Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+242',
        ),
        array(
            'name' => 'Congo (DRC)',
            'code' => 'CD',
            'timezone' => 'W. Central Africa Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+243',
        ),
        array(
            'name' => 'Cook Islands',
            'code' => 'CK',
            'timezone' => 'Hawaiian Standard Time',
            'utc' => 'UTC-10:00',
            'mobileCode' => '+682',
        ),
        array(
            'name' => 'Costa Rica',
            'code' => 'CR',
            'timezone' => 'Central America Standard Time',
            'utc' => 'UTC-06:00',
            'mobileCode' => '+506',
        ),
        array(
            'name' => 'Côte d\'Ivoire',
            'code' => 'CI',
            'timezone' => 'Greenwich Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+225',
        ),
        array(
            'name' => 'Croatia',
            'code' => 'HR',
            'timezone' => 'Central European Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+385',
        ),
        array(
            'name' => 'Cuba',
            'code' => 'CU',
            'timezone' => 'Eastern Standard Time',
            'utc' => 'UTC-05:00',
            'mobileCode' => '+53',
        ),
        array(
            'name' => 'Curaçao',
            'code' => 'CW',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+599',
        ),
        array(
            'name' => 'Cyprus',
            'code' => 'CY',
            'timezone' => 'E. Europe Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+357',
        ),
        array(
            'name' => 'Czech Republic',
            'code' => 'CZ',
            'timezone' => 'Central Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+420',
        ),
        array(
            'name' => 'Democratic Republic of Timor-Leste',
            'code' => 'TL',
            'timezone' => 'Tokyo Standard Time',
            'utc' => 'UTC+09:00',
            'mobileCode' => '+670',
        ),
        array(
            'name' => 'Denmark',
            'code' => 'DK',
            'timezone' => 'Romance Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+45',
        ),
        array(
            'name' => 'Djibouti',
            'code' => 'DJ',
            'timezone' => 'E. Africa Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+253',
        ),
        array(
            'name' => 'Dominica',
            'code' => 'DM',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+1-767',
        ),
        array(
            'name' => 'Dominican Republic',
            'code' => 'DO',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+1-809 and 1-829',
        ),
        array(
            'name' => 'Ecuador',
            'code' => 'EC',
            'timezone' => 'SA Pacific Standard Time',
            'utc' => 'UTC-05:00',
            'mobileCode' => '+593',
        ),
        array(
            'name' => 'Egypt',
            'code' => 'EG',
            'timezone' => 'Egypt Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+20',
        ),
        array(
            'name' => 'El Salvador',
            'code' => 'SV',
            'timezone' => 'Central America Standard Time',
            'utc' => 'UTC-06:00',
            'mobileCode' => '+503',
        ),
        array(
            'name' => 'Equatorial Guinea',
            'code' => 'GQ',
            'timezone' => 'W. Central Africa Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+240',
        ),
        array(
            'name' => 'Eritrea',
            'code' => 'ER',
            'timezone' => 'E. Africa Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+291',
        ),
        array(
            'name' => 'Estonia',
            'code' => 'EE',
            'timezone' => 'FLE Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+372',
        ),
        array(
            'name' => 'Ethiopia',
            'code' => 'ET',
            'timezone' => 'E. Africa Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+251',
        ),
        array(
            'name' => 'Falkland Islands (Islas Malvinas)',
            'code' => 'FK',
            'timezone' => 'SA Eastern Standard Time',
            'utc' => 'UTC-03:00',
            'mobileCode' => '+500',
        ),
        array(
            'name' => 'Faroe Islands',
            'code' => 'FO',
            'timezone' => 'GMT Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+298',
        ),
        array(
            'name' => 'Fiji Islands',
            'code' => 'FJ',
            'timezone' => 'Fiji Standard Time',
            'utc' => 'UTC+12:00',
            'mobileCode' => '+679',
        ),
        array(
            'name' => 'Finland',
            'code' => 'FI',
            'timezone' => 'FLE Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+358',
        ),
        array(
            'name' => 'France',
            'code' => 'FR',
            'timezone' => 'Romance Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+33',
        ),
        array(
            'name' => 'French Guiana',
            'code' => 'GF',
            'timezone' => 'SA Eastern Standard Time',
            'utc' => 'UTC-03:00',
            'mobileCode' => '+594',
        ),
        array(
            'name' => 'French Polynesia',
            'code' => 'PF',
            'timezone' => 'Hawaiian Standard Time',
            'utc' => 'UTC-10:00',
            'mobileCode' => '+689',
        ),
        array(
            'name' => 'French Southern and Antarctic Lands',
            'code' => 'TF',
            'timezone' => 'West Asia Standard Time',
            'utc' => 'UTC+05:00',
            'mobileCode' => '+',
        ),
        array(
            'name' => 'Gabon',
            'code' => 'GA',
            'timezone' => 'W. Central Africa Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+241',
        ),
        array(
            'name' => 'Gambia, The',
            'code' => 'GM',
            'timezone' => 'Greenwich Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+220',
        ),
        array(
            'name' => 'Georgia',
            'code' => 'GE',
            'timezone' => 'Georgian Standard Time',
            'utc' => 'UTC+04:00',
            'mobileCode' => '+995',
        ),
        array(
            'name' => 'Germany',
            'code' => 'DE',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+49',
        ),
        array(
            'name' => 'Ghana',
            'code' => 'GH',
            'timezone' => 'Greenwich Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+233',
        ),
        array(
            'name' => 'Gibraltar',
            'code' => 'GI',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+350',
        ),
        array(
            'name' => 'Greece',
            'code' => 'GR',
            'timezone' => 'GTB Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+30',
        ),
        array(
            'name' => 'Greenland',
            'code' => 'GL',
            'timezone' => 'Greenland Standard Time',
            'utc' => 'UTC-03:00',
            'mobileCode' => '+299',
        ),
        array(
            'name' => 'Grenada',
            'code' => 'GD',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+1-473',
        ),
        array(
            'name' => 'Guadeloupe',
            'code' => 'GP',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+590',
        ),
        array(
            'name' => 'Guam',
            'code' => 'GU',
            'timezone' => 'West Pacific Standard Time',
            'utc' => 'UTC+10:00',
            'mobileCode' => '+1-671',
        ),
        array(
            'name' => 'Guatemala',
            'code' => 'GT',
            'timezone' => 'Central America Standard Time',
            'utc' => 'UTC-06:00',
            'mobileCode' => '+502',
        ),
        array(
            'name' => 'Guernsey',
            'code' => 'GG',
            'timezone' => 'GMT Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+44-1481',
        ),
        array(
            'name' => 'Guinea',
            'code' => 'GN',
            'timezone' => 'Greenwich Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+224',
        ),
        array(
            'name' => 'Guinea-Bissau',
            'code' => 'GW',
            'timezone' => 'Greenwich Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+245',
        ),
        array(
            'name' => 'Guyana',
            'code' => 'GY',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+592',
        ),
        array(
            'name' => 'Haiti',
            'code' => 'HT',
            'timezone' => 'Eastern Standard Time',
            'utc' => 'UTC-05:00',
            'mobileCode' => '+509',
        ),
        array(
            'name' => 'Heard Island and McDonald Islands',
            'code' => 'HM',
            'timezone' => 'Mauritius Standard Time',
            'utc' => 'UTC+04:00',
            'mobileCode' => '+ ',
        ),
        array(
            'name' => 'Honduras',
            'code' => 'HN',
            'timezone' => 'Central America Standard Time',
            'utc' => 'UTC-06:00',
            'mobileCode' => '+504',
        ),
        array(
            'name' => 'Hong Kong SAR',
            'code' => 'HK',
            'timezone' => 'China Standard Time',
            'utc' => 'UTC+08:00',
            'mobileCode' => '+852',
        ),
        array(
            'name' => 'Hungary',
            'code' => 'HU',
            'timezone' => 'Central Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+36',
        ),
        array(
            'name' => 'Iceland',
            'code' => 'IS',
            'timezone' => 'Greenwich Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+354',
        ),
        array(
            'name' => 'India',
            'code' => 'IN',
            'timezone' => 'India Standard Time',
            'utc' => 'UTC+05:30',
            'mobileCode' => '+91',
        ),
        array(
            'name' => 'Indonesia',
            'code' => 'ID',
            'timezone' => 'SE Asia Standard Time',
            'utc' => 'UTC+07:00',
            'mobileCode' => '+62',
        ),
        array(
            'name' => 'Iran',
            'code' => 'IR',
            'timezone' => 'Iran Standard Time',
            'utc' => 'UTC+03:30',
            'mobileCode' => '+98',
        ),
        array(
            'name' => 'Iraq',
            'code' => 'IQ',
            'timezone' => 'Arabic Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+964',
        ),
        array(
            'name' => 'Ireland',
            'code' => 'IE',
            'timezone' => 'GMT Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+353',
        ),
        array(
            'name' => 'Italy',
            'code' => 'IT',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+39',
        ),
        array(
            'name' => 'Jamaica',
            'code' => 'JM',
            'timezone' => 'SA Pacific Standard Time',
            'utc' => 'UTC-05:00',
            'mobileCode' => '+1-876',
        ),
        array(
            'name' => 'Jan Mayen',
            'code' => 'SJ',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+47',
        ),
        array(
            'name' => 'Japan',
            'code' => 'JP',
            'timezone' => 'Tokyo Standard Time',
            'utc' => 'UTC+09:00',
            'mobileCode' => '+81',
        ),
        array(
            'name' => 'Jersey',
            'code' => 'JE',
            'timezone' => 'GMT Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+44-1534',
        ),
        array(
            'name' => 'Jordan',
            'code' => 'JO',
            'timezone' => 'Jordan Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+962',
        ),
        array(
            'name' => 'Kazakhstan',
            'code' => 'KZ',
            'timezone' => 'Central Asia Standard Time',
            'utc' => 'UTC+06:00',
            'mobileCode' => '+7',
        ),
        array(
            'name' => 'Kenya',
            'code' => 'KE',
            'timezone' => 'E. Africa Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+254',
        ),
        array(
            'name' => 'Kiribati',
            'code' => 'KI',
            'timezone' => 'UTC+12',
            'utc' => 'UTC+12:00',
            'mobileCode' => '+686',
        ),
        array(
            'name' => 'Korea',
            'code' => 'KR',
            'timezone' => 'Korea Standard Time',
            'utc' => 'UTC+09:00',
            'mobileCode' => '+82',
        ),
        array(
            'name' => 'Kosovo',
            'code' => 'XK',
            'timezone' => 'Central European Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+',
        ),
        array(
            'name' => 'Kuwait',
            'code' => 'KW',
            'timezone' => 'Arab Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+965',
        ),
        array(
            'name' => 'Kyrgyzstan',
            'code' => 'KG',
            'timezone' => 'Central Asia Standard Time',
            'utc' => 'UTC+06:00',
            'mobileCode' => '+996',
        ),
        array(
            'name' => 'Laos',
            'code' => 'LA',
            'timezone' => 'SE Asia Standard Time',
            'utc' => 'UTC+07:00',
            'mobileCode' => '+856',
        ),
        array(
            'name' => 'Latvia',
            'code' => 'LV',
            'timezone' => 'FLE Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+371',
        ),
        array(
            'name' => 'Lebanon',
            'code' => 'LB',
            'timezone' => 'Middle East Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+961',
        ),
        array(
            'name' => 'Lesotho',
            'code' => 'LS',
            'timezone' => 'South Africa Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+266',
        ),
        array(
            'name' => 'Liberia',
            'code' => 'LR',
            'timezone' => 'Greenwich Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+231',
        ),
        array(
            'name' => 'Libya',
            'code' => 'LY',
            'timezone' => 'E. Europe Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+218',
        ),
        array(
            'name' => 'Liechtenstein',
            'code' => 'LI',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+423',
        ),
        array(
            'name' => 'Lithuania',
            'code' => 'LT',
            'timezone' => 'FLE Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+370',
        ),
        array(
            'name' => 'Luxembourg',
            'code' => 'LU',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+352',
        ),
        array(
            'name' => 'Macao SAR',
            'code' => 'MO',
            'timezone' => 'China Standard Time',
            'utc' => 'UTC+08:00',
            'mobileCode' => '+853',
        ),
        array(
            'name' => 'Macedonia, Former Yugoslav Republic of',
            'code' => 'MK',
            'timezone' => 'Central European Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+389',
        ),
        array(
            'name' => 'Madagascar',
            'code' => 'MG',
            'timezone' => 'E. Africa Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+261',
        ),
        array(
            'name' => 'Malawi',
            'code' => 'MW',
            'timezone' => 'South Africa Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+265',
        ),
        array(
            'name' => 'Malaysia',
            'code' => 'MY',
            'timezone' => 'Singapore Standard Time',
            'utc' => 'UTC+08:00',
            'mobileCode' => '+60',
        ),
        array(
            'name' => 'Maldives',
            'code' => 'MV',
            'timezone' => 'West Asia Standard Time',
            'utc' => 'UTC+05:00',
            'mobileCode' => '+960',
        ),
        array(
            'name' => 'Mali',
            'code' => 'ML',
            'timezone' => 'Greenwich Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+223',
        ),
        array(
            'name' => 'Malta',
            'code' => 'MT',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+356',
        ),
        array(
            'name' => 'Man, Isle of',
            'code' => 'IM',
            'timezone' => 'GMT Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+44-1624',
        ),
        array(
            'name' => 'Marshall Islands',
            'code' => 'MH',
            'timezone' => 'UTC+12',
            'utc' => 'UTC+12:00',
            'mobileCode' => '+692',
        ),
        array(
            'name' => 'Martinique',
            'code' => 'MQ',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+596',
        ),
        array(
            'name' => 'Mauritania',
            'code' => 'MR',
            'timezone' => 'Greenwich Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+222',
        ),
        array(
            'name' => 'Mauritius',
            'code' => 'MU',
            'timezone' => 'Mauritius Standard Time',
            'utc' => 'UTC+04:00',
            'mobileCode' => '+230',
        ),
        array(
            'name' => 'Mayotte',
            'code' => 'YT',
            'timezone' => 'E. Africa Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+262',
        ),
        array(
            'name' => 'Mexico',
            'code' => 'MX',
            'timezone' => 'Central Standard Time (Mexico)',
            'utc' => 'UTC-06:00',
            'mobileCode' => '+52',
        ),
        array(
            'name' => 'Micronesia',
            'code' => 'FM',
            'timezone' => 'West Pacific Standard Time',
            'utc' => 'UTC+10:00',
            'mobileCode' => '+691',
        ),
        array(
            'name' => 'Moldova',
            'code' => 'MD',
            'timezone' => 'GTB Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+373',
        ),
        array(
            'name' => 'Monaco',
            'code' => 'MC',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+377',
        ),
        array(
            'name' => 'Mongolia',
            'code' => 'MN',
            'timezone' => 'Ulaanbaatar Standard Time',
            'utc' => 'UTC+08:00',
            'mobileCode' => '+976',
        ),
        array(
            'name' => 'Montenegro',
            'code' => 'ME',
            'timezone' => 'Central European Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+382',
        ),
        array(
            'name' => 'Montserrat',
            'code' => 'MS',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+1-664',
        ),
        array(
            'name' => 'Morocco',
            'code' => 'MA',
            'timezone' => 'Morocco Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+212',
        ),
        array(
            'name' => 'Mozambique',
            'code' => 'MZ',
            'timezone' => 'South Africa Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+258',
        ),
        array(
            'name' => 'Myanmar',
            'code' => 'MM',
            'timezone' => 'Myanmar Standard Time',
            'utc' => 'UTC+06:30',
            'mobileCode' => '+95',
        ),
        array(
            'name' => 'Namibia',
            'code' => 'NA',
            'timezone' => 'Namibia Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+264',
        ),
        array(
            'name' => 'Nauru',
            'code' => 'NR',
            'timezone' => 'UTC+12',
            'utc' => 'UTC+12:00',
            'mobileCode' => '+674',
        ),
        array(
            'name' => 'Nepal',
            'code' => 'NP',
            'timezone' => 'Nepal Standard Time',
            'utc' => 'UTC+05:45',
            'mobileCode' => '+977',
        ),
        array(
            'name' => 'Netherlands',
            'code' => 'NL',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+31',
        ),
        array(
            'name' => 'New Caledonia',
            'code' => 'NC',
            'timezone' => 'Central Pacific Standard Time',
            'utc' => 'UTC+11:00',
            'mobileCode' => '+687',
        ),
        array(
            'name' => 'New Zealand',
            'code' => 'NZ',
            'timezone' => 'New Zealand Standard Time',
            'utc' => 'UTC+12:00',
            'mobileCode' => '+64',
        ),
        array(
            'name' => 'Nicaragua',
            'code' => 'NI',
            'timezone' => 'Central America Standard Time',
            'utc' => 'UTC-06:00',
            'mobileCode' => '+505',
        ),
        array(
            'name' => 'Niger',
            'code' => 'NE',
            'timezone' => 'W. Central Africa Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+227',
        ),
        array(
            'name' => 'Nigeria',
            'code' => 'NG',
            'timezone' => 'W. Central Africa Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+234',
        ),
        array(
            'name' => 'Niue',
            'code' => 'NU',
            'timezone' => 'UTC-11',
            'utc' => 'UTC-11:00',
            'mobileCode' => '+683',
        ),
        array(
            'name' => 'Norfolk Island',
            'code' => 'NF',
            'timezone' => 'Central Pacific Standard Time',
            'utc' => 'UTC+11:00',
            'mobileCode' => '+672',
        ),
        array(
            'name' => 'North Korea',
            'code' => 'KP',
            'timezone' => 'Korea Standard Time',
            'utc' => 'UTC+09:00',
            'mobileCode' => '+850',
        ),
        array(
            'name' => 'Northern Mariana Islands',
            'code' => 'MP',
            'timezone' => 'West Pacific Standard Time',
            'utc' => 'UTC+10:00',
            'mobileCode' => '+1-670',
        ),
        array(
            'name' => 'Norway',
            'code' => 'NO',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+47',
        ),
        array(
            'name' => 'Oman',
            'code' => 'OM',
            'timezone' => 'Arabian Standard Time',
            'utc' => 'UTC+04:00',
            'mobileCode' => '+968',
        ),
        array(
            'name' => 'Pakistan',
            'code' => 'PK',
            'timezone' => 'Pakistan Standard Time',
            'utc' => 'UTC+05:00',
            'mobileCode' => '+92',
        ),
        array(
            'name' => 'Palau',
            'code' => 'PW',
            'timezone' => 'Tokyo Standard Time',
            'utc' => 'UTC+09:00',
            'mobileCode' => '+680',
        ),
        array(
            'name' => 'Palestinian Authority',
            'code' => 'PS',
            'timezone' => 'Egypt Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+970',
        ),
        array(
            'name' => 'Panama',
            'code' => 'PA',
            'timezone' => 'SA Pacific Standard Time',
            'utc' => 'UTC-05:00',
            'mobileCode' => '+507',
        ),
        array(
            'name' => 'Papua New Guinea',
            'code' => 'PG',
            'timezone' => 'West Pacific Standard Time',
            'utc' => 'UTC+10:00',
            'mobileCode' => '+675',
        ),
        array(
            'name' => 'Paraguay',
            'code' => 'PY',
            'timezone' => 'Paraguay Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+595',
        ),
        array(
            'name' => 'Peru',
            'code' => 'PE',
            'timezone' => 'SA Pacific Standard Time',
            'utc' => 'UTC-05:00',
            'mobileCode' => '+51',
        ),
        array(
            'name' => 'Philippines',
            'code' => 'PH',
            'timezone' => 'Singapore Standard Time',
            'utc' => 'UTC+08:00',
            'mobileCode' => '+63',
        ),
        array(
            'name' => 'Pitcairn Islands',
            'code' => 'PN',
            'timezone' => 'Pacific Standard Time',
            'utc' => 'UTC-08:00',
            'mobileCode' => '+870',
        ),
        array(
            'name' => 'Poland',
            'code' => 'PL',
            'timezone' => 'Central European Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+48',
        ),
        array(
            'name' => 'Portugal',
            'code' => 'PT',
            'timezone' => 'GMT Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+351',
        ),
        array(
            'name' => 'Puerto Rico',
            'code' => 'PR',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+1-787 and 1-939',
        ),
        array(
            'name' => 'Qatar',
            'code' => 'QA',
            'timezone' => 'Arab Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+974',
        ),
        array(
            'name' => 'Reunion',
            'code' => 'RE',
            'timezone' => 'Mauritius Standard Time',
            'utc' => 'UTC+04:00',
            'mobileCode' => '+262',
        ),
        array(
            'name' => 'Romania',
            'code' => 'RO',
            'timezone' => 'GTB Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+40',
        ),
        array(
            'name' => 'Russia',
            'code' => 'RU',
            'timezone' => 'Russian Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+7',
        ),
        array(
            'name' => 'Rwanda',
            'code' => 'RW',
            'timezone' => 'South Africa Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+250',
        ),
        array(
            'name' => 'Saint Barthélemy',
            'code' => 'BL',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+590',
        ),
        array(
            'name' => 'Saint Helena, Ascension and Tristan da Cunha',
            'code' => 'SH',
            'timezone' => 'Greenwich Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+290',
        ),
        array(
            'name' => 'Saint Kitts and Nevis',
            'code' => 'KN',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+1-869',
        ),
        array(
            'name' => 'Saint Lucia',
            'code' => 'LC',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+1-758',
        ),
        array(
            'name' => 'Saint Martin (French part)',
            'code' => 'MF',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+590',
        ),
        array(
            'name' => 'Saint Pierre and Miquelon',
            'code' => 'PM',
            'timezone' => 'Greenland Standard Time',
            'utc' => 'UTC-03:00',
            'mobileCode' => '+508',
        ),
        array(
            'name' => 'Saint Vincent and the Grenadines',
            'code' => 'VC',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+1-784',
        ),
        array(
            'name' => 'Samoa',
            'code' => 'WS',
            'timezone' => 'Samoa Standard Time',
            'utc' => 'UTC+13:00',
            'mobileCode' => '+685',
        ),
        array(
            'name' => 'San Marino',
            'code' => 'SM',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+378',
        ),
        array(
            'name' => 'São Tomé and Príncipe',
            'code' => 'ST',
            'timezone' => 'Greenwich Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+239',
        ),
        array(
            'name' => 'Saudi Arabia',
            'code' => 'SA',
            'timezone' => 'Arab Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+966',
        ),
        array(
            'name' => 'Senegal',
            'code' => 'SN',
            'timezone' => 'Greenwich Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+221',
        ),
        array(
            'name' => 'Serbia',
            'code' => 'RS',
            'timezone' => 'Central Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+381',
        ),
        array(
            'name' => 'Seychelles',
            'code' => 'SC',
            'timezone' => 'Mauritius Standard Time',
            'utc' => 'UTC+04:00',
            'mobileCode' => '+248',
        ),
        array(
            'name' => 'Sierra Leone',
            'code' => 'SL',
            'timezone' => 'Greenwich Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+232',
        ),
        array(
            'name' => 'Singapore',
            'code' => 'SG',
            'timezone' => 'Singapore Standard Time',
            'utc' => 'UTC+08:00',
            'mobileCode' => '+65',
        ),
        array(
            'name' => 'Sint Maarten (Dutch part)',
            'code' => 'SX',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+599',
        ),
        array(
            'name' => 'Slovakia',
            'code' => 'SK',
            'timezone' => 'Central Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+421',
        ),
        array(
            'name' => 'Slovenia',
            'code' => 'SI',
            'timezone' => 'Central Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+386',
        ),
        array(
            'name' => 'Solomon Islands',
            'code' => 'SB',
            'timezone' => 'Central Pacific Standard Time',
            'utc' => 'UTC+11:00',
            'mobileCode' => '+677',
        ),
        array(
            'name' => 'Somalia',
            'code' => 'SO',
            'timezone' => 'E. Africa Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+252',
        ),
        array(
            'name' => 'South Africa',
            'code' => 'ZA',
            'timezone' => 'South Africa Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+27',
        ),
        array(
            'name' => 'South Georgia and the South Sandwich Islands',
            'code' => 'GS',
            'timezone' => 'UTC-02',
            'utc' => 'UTC-02:00',
            'mobileCode' => '+',
        ),
        array(
            'name' => 'South Sudan',
            'code' => 'SS',
            'timezone' => 'E. Africa Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+211',
        ),
        array(
            'name' => 'Spain',
            'code' => 'ES',
            'timezone' => 'Romance Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+34',
        ),
        array(
            'name' => 'Sri Lanka',
            'code' => 'LK',
            'timezone' => 'Sri Lanka Standard Time',
            'utc' => 'UTC+05:30',
            'mobileCode' => '+94',
        ),
        array(
            'name' => 'Sudan',
            'code' => 'SD',
            'timezone' => 'E. Africa Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+249',
        ),
        array(
            'name' => 'Suriname',
            'code' => 'SR',
            'timezone' => 'SA Eastern Standard Time',
            'utc' => 'UTC-03:00',
            'mobileCode' => '+597',
        ),
        array(
            'name' => 'Svalbard',
            'code' => 'SJ',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+47',
        ),
        array(
            'name' => 'Swaziland',
            'code' => 'SZ',
            'timezone' => 'South Africa Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+268',
        ),
        array(
            'name' => 'Sweden',
            'code' => 'SE',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+46',
        ),
        array(
            'name' => 'Switzerland',
            'code' => 'CH',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+41',
        ),
        array(
            'name' => 'Syria',
            'code' => 'SY',
            'timezone' => 'Syria Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+963',
        ),
        array(
            'name' => 'Taiwan',
            'code' => 'TW',
            'timezone' => 'Taipei Standard Time',
            'utc' => 'UTC+08:00',
            'mobileCode' => '+886',
        ),
        array(
            'name' => 'Tajikistan',
            'code' => 'TJ',
            'timezone' => 'West Asia Standard Time',
            'utc' => 'UTC+05:00',
            'mobileCode' => '+992',
        ),
        array(
            'name' => 'Tanzania',
            'code' => 'TZ',
            'timezone' => 'E. Africa Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+255',
        ),
        array(
            'name' => 'Thailand',
            'code' => 'TH',
            'timezone' => 'SE Asia Standard Time',
            'utc' => 'UTC+07:00',
            'mobileCode' => '+66',
        ),
        array(
            'name' => 'Togo',
            'code' => 'TG',
            'timezone' => 'Greenwich Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+228',
        ),
        array(
            'name' => 'Tokelau',
            'code' => 'TK',
            'timezone' => 'Tonga Standard Time',
            'utc' => 'UTC+13:00',
            'mobileCode' => '+690',
        ),
        array(
            'name' => 'Tonga',
            'code' => 'TO',
            'timezone' => 'Tonga Standard Time',
            'utc' => 'UTC+13:00',
            'mobileCode' => '+676',
        ),
        array(
            'name' => 'Trinidad and Tobago',
            'code' => 'TT',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+1-868',
        ),
        array(
            'name' => 'Tunisia',
            'code' => 'TN',
            'timezone' => 'W. Central Africa Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+216',
        ),
        array(
            'name' => 'Turkey',
            'code' => 'TR',
            'timezone' => 'Turkey Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+90',
        ),
        array(
            'name' => 'Turkmenistan',
            'code' => 'TM',
            'timezone' => 'West Asia Standard Time',
            'utc' => 'UTC+05:00',
            'mobileCode' => '+993',
        ),
        array(
            'name' => 'Turks and Caicos Islands',
            'code' => 'TC',
            'timezone' => 'Eastern Standard Time',
            'utc' => 'UTC-05:00',
            'mobileCode' => '+1-649',
        ),
        array(
            'name' => 'Tuvalu',
            'code' => 'TV',
            'timezone' => 'UTC+12',
            'utc' => 'UTC+12:00',
            'mobileCode' => '+688',
        ),
        array(
            'name' => 'U.S. Minor Outlying Islands',
            'code' => 'UM',
            'timezone' => 'UTC-11',
            'utc' => 'UTC-11:00',
            'mobileCode' => '+1',
        ),
        array(
            'name' => 'Uganda',
            'code' => 'UG',
            'timezone' => 'E. Africa Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+256',
        ),
        array(
            'name' => 'Ukraine',
            'code' => 'UA',
            'timezone' => 'FLE Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+380',
        ),
        array(
            'name' => 'United Arab Emirates',
            'code' => 'AE',
            'timezone' => 'Arabian Standard Time',
            'utc' => 'UTC+04:00',
            'mobileCode' => '+971',
        ),
        array(
            'name' => 'United Kingdom',
            'code' => 'GB',
            'timezone' => 'GMT Standard Time',
            'utc' => 'UTC',
            'mobileCode' => '+44',
        ),
        array(
            'name' => 'United States',
            'code' => 'US',
            'timezone' => 'Pacific Standard Time',
            'utc' => 'UTC-08:00',
            'mobileCode' => '+1',
        ),
        array(
            'name' => 'Uruguay',
            'code' => 'UY',
            'timezone' => 'Montevideo Standard Time',
            'utc' => 'UTC-03:00',
            'mobileCode' => '+598',
        ),
        array(
            'name' => 'Uzbekistan',
            'code' => 'UZ',
            'timezone' => 'West Asia Standard Time',
            'utc' => 'UTC+05:00',
            'mobileCode' => '+998',
        ),
        array(
            'name' => 'Vanuatu',
            'code' => 'VU',
            'timezone' => 'Central Pacific Standard Time',
            'utc' => 'UTC+11:00',
            'mobileCode' => '+678',
        ),
        array(
            'name' => 'Vatican City',
            'code' => 'VA',
            'timezone' => 'W. Europe Standard Time',
            'utc' => 'UTC+01:00',
            'mobileCode' => '+379',
        ),
        array(
            'name' => 'Vietnam',
            'code' => 'VN',
            'timezone' => 'SE Asia Standard Time',
            'utc' => 'UTC+07:00',
            'mobileCode' => '+84',
        ),
        array(
            'name' => 'Virgin Islands, U.S.',
            'code' => 'VI',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+1-340',
        ),
        array(
            'name' => 'Virgin Islands, British',
            'code' => 'VG',
            'timezone' => 'SA Western Standard Time',
            'utc' => 'UTC-04:00',
            'mobileCode' => '+1-284',
        ),
        array(
            'name' => 'Wallis and Futuna',
            'code' => 'WF',
            'timezone' => 'UTC+12',
            'utc' => 'UTC+12:00',
            'mobileCode' => '+681',
        ),
        array(
            'name' => 'Yemen',
            'code' => 'YE',
            'timezone' => 'Arab Standard Time',
            'utc' => 'UTC+03:00',
            'mobileCode' => '+967',
        ),
        array(
            'name' => 'Zambia',
            'code' => 'ZM',
            'timezone' => 'South Africa Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+260',
        ),
        array(
            'name' => 'Zimbabwe',
            'code' => 'ZW',
            'timezone' => 'South Africa Standard Time',
            'utc' => 'UTC+02:00',
            'mobileCode' => '+263',
        ),
    ]
];
